### ISSUE TITLE
Do you have plan to support RV32 set?

### ISSUE THREAD

**Issue by Cranexiao95** [sparcians/mavis#12]
I found there is only rv64 isa set in json folder. I meet some rv32 instructions (c.jal) and it is fail to decode.
Do you have any plan to support rv32?

**Comment by kathlenemagnus** [comment]
I have implemented RV32 and plan to upstream the support within the next couple of weeks.

**Comment by kathlenemagnus** [comment]
@Cranexiao95 I released support for RV32. However, it is only lightly tested so proceed with caution! Please create an issue and assign it to me if you find any bugs.
