### ISSUE TITLE
Is the miss vector segment load/store isa defintion?

### ISSUE THREAD

**Issue by lhtin** [sparcians/mavis#8]
The vector segment load/store definition seems to be missing inside this [file](https://github.com/sparcians/mavis/blob/main/json/isa_rv64v.json), or is it somewhere else? Thanks.

**Comment by klingaard** [comment]
In other words, Mavis will decode them, but will set various attributes in the return opcode info.  See example: https://github.com/sparcians/mavis/blob/2d098024a2fcb5e54123d518a611436017159edc/test/main.cpp#L619-L625
